[versions]
java = "21"

minecraft = "1.21.4"
yarn = "1"

neoforge = "111-beta"
fabric_loader = "0.16.10"

mixin = "0.8.5"
mixin_extra = "0.3.2"

asm = "9.7.1"
prism4j = "2.0.0"
joor = "0.9.15"
nv_websocket = "2.14"
fapi = "0.100.1+1.21"
modmenu = "11.0.0-beta.1"
junit = "5.8.1"
jb_annotations = "20.1.0"
javassist = "3.30.2-GA"

shadow = "8.3.6"

[libraries]
prism4j = { module = "io.noties:prism4j", version.ref = "prism4j" }

mixin = { module = "org.spongepowered:mixin", version.ref = "mixin" }
mixin_extra = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixin_extra" }

asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
joor = { module = "org.jooq:joor", version.ref = "joor" }
nv_websocket = { module = "com.neovisionaries:nv-websocket-client", version.ref = "nv_websocket" }
javassist = { module = "org.javassist:javassist", version.ref = "javassist" }

modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

junit_api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit_engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

jb_annotations = { module = "org.jetbrains:annotations", version.ref = "jb_annotations" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
